// Comprehensive dataset reflecting the exact screens from the AltIndex reference image

export const USER_PROFILE = {
  name: 'Alex Smith',
  email: 'alexsmith16@gmail.com',
  role: 'Fund Manager',
  plan: 'Professional Tier',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  notificationsCount: 4
};

// Screen 6 & 7: Top Stocks - AI Screener Table
export const TOP_STOCKS_DATA = [
  {
    id: 'twtr',
    name: 'Twitter',
    symbol: 'TWTR',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/twitter/twitter-original.svg',
    initial: 'T',
    color: '#1DA1F2',
    price: 254.17,
    priceChange: -4.8,
    marketCap: '50.2B',
    aiScore: 85,
    scoreChange: 5.2,
    rating: 'BUY',
    industry: 'Social Media',
    sentiment: 82,
    downloads: '1.2M',
    peRatio: 38.4
  },
  {
    id: 'spot',
    name: 'Spotify',
    symbol: 'SPOT',
    logo: '',
    initial: 'S',
    color: '#1ED760',
    price: 56.81,
    priceChange: 1.7,
    marketCap: '529.72B',
    aiScore: 79,
    scoreChange: 2.0,
    rating: 'SELL',
    industry: 'Entertainment & Audio',
    sentiment: 64,
    downloads: '425.7K',
    peRatio: 44.1
  },
  {
    id: 'aapl',
    name: 'Apple',
    symbol: 'AAPL',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg',
    initial: 'A',
    color: '#000000',
    price: 187.50,
    priceChange: -2.3,
    marketCap: '487.64B',
    aiScore: 72,
    scoreChange: 1.0,
    rating: 'BUY',
    industry: 'Consumer Technology',
    sentiment: 78,
    downloads: '8.4M',
    peRatio: 29.5
  },
  {
    id: 'open',
    name: 'OpenDoor',
    symbol: 'OPEN',
    logo: '',
    initial: 'O',
    color: '#10529D',
    price: 12.43,
    priceChange: 5.8,
    marketCap: '323.4B',
    aiScore: 72,
    scoreChange: -3.0,
    rating: 'HOLD',
    industry: 'Real Estate Tech',
    sentiment: 51,
    downloads: '84.2K',
    peRatio: 18.2
  },
  {
    id: 'msft',
    name: 'Microsoft',
    symbol: 'MSFT',
    logo: '',
    initial: 'M',
    color: '#00A4EF',
    price: 112.48,
    priceChange: 2.0,
    marketCap: '365.6B',
    aiScore: 78,
    scoreChange: 4.2,
    rating: 'SELL',
    industry: 'Enterprise Software',
    sentiment: 74,
    downloads: '3.1M',
    peRatio: 34.0
  },
  {
    id: 'googl',
    name: 'Google',
    symbol: 'GOOGL',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
    initial: 'G',
    color: '#EA4335',
    price: 523.54,
    priceChange: 1.4,
    marketCap: '329.54B',
    aiScore: 75,
    scoreChange: 1.8,
    rating: 'BUY',
    industry: 'Internet & Search',
    sentiment: 81,
    downloads: '14.2M',
    peRatio: 26.8
  },
  {
    id: 'zm',
    name: 'Zoom',
    symbol: 'ZM',
    logo: '',
    initial: 'Z',
    color: '#2D8CFF',
    price: 5.11,
    priceChange: 1.2,
    marketCap: '487.64B',
    aiScore: 75,
    scoreChange: 6.7,
    rating: 'BUY',
    industry: 'Communications',
    sentiment: 69,
    downloads: '920.4K',
    peRatio: 21.3
  },
  {
    id: 'open2',
    name: 'OpenDoor Technologies',
    symbol: 'OPEN',
    logo: '',
    initial: 'O',
    color: '#0070F3',
    price: 349.63,
    priceChange: -2.7,
    marketCap: '487.64B',
    aiScore: 73,
    scoreChange: 8.1,
    rating: 'BUY',
    industry: 'Real Estate Tech',
    sentiment: 66,
    downloads: '112.0K',
    peRatio: 19.4
  },
  {
    id: 'nke1',
    name: 'Nike',
    symbol: 'NKE',
    logo: '',
    initial: 'N',
    color: '#111111',
    price: 10.08,
    priceChange: 2.1,
    marketCap: '487.64B',
    aiScore: 74,
    scoreChange: 0.0,
    rating: 'HOLD',
    industry: 'Retail & Apparel',
    sentiment: 62,
    downloads: '890.1K',
    peRatio: 28.7
  },
  {
    id: 'nke2',
    name: 'Nike Direct',
    symbol: 'NKE',
    logo: '',
    initial: 'N',
    color: '#F97316',
    price: 252.33,
    priceChange: 0.5,
    marketCap: '487.64B',
    aiScore: 70,
    scoreChange: 0.0,
    rating: 'SELL',
    industry: 'Retail & Apparel',
    sentiment: 58,
    downloads: '1.4M',
    peRatio: 31.2
  },
  {
    id: 'nflx',
    name: 'Netflix',
    symbol: 'NFLX',
    logo: '',
    initial: 'N',
    color: '#E50914',
    price: 397.42,
    priceChange: 4.2,
    marketCap: '204.1B',
    aiScore: 88,
    scoreChange: 3.4,
    rating: 'BUY',
    industry: 'Entertainment & Streaming',
    sentiment: 84,
    downloads: '257,892',
    peRatio: 31.8
  },
  {
    id: 'qdel',
    name: 'QuidelOrtho',
    symbol: 'QDEL',
    logo: '',
    initial: 'Q',
    color: '#0EA5E9',
    price: 147.96,
    priceChange: 4.2,
    marketCap: '12.8B',
    aiScore: 81,
    scoreChange: 1.9,
    rating: 'BUY',
    industry: 'Healthcare Diagnostics',
    sentiment: 77,
    downloads: '45.0K',
    peRatio: 16.5
  },
  {
    id: 'mtch',
    name: 'Match Group',
    symbol: 'MTCH',
    logo: '',
    initial: 'M',
    color: '#EC4899',
    price: 127.12,
    priceChange: 2.1,
    marketCap: '34.5B',
    aiScore: 76,
    scoreChange: 2.1,
    rating: 'BUY',
    industry: 'Social & Dating',
    sentiment: 68,
    downloads: '1.8M',
    peRatio: 22.4
  },
  {
    id: 'len',
    name: 'Lennar Corp',
    symbol: 'LEN',
    logo: '',
    initial: 'L',
    color: '#6366F1',
    price: 94.50,
    priceChange: 7.8,
    marketCap: '28.2B',
    aiScore: 79,
    scoreChange: 7.8,
    rating: 'BUY',
    industry: 'Construction & Housing',
    sentiment: 72,
    downloads: '18.4K',
    peRatio: 11.2
  },
  {
    id: 'eb',
    name: 'Eventbrite',
    symbol: 'EB',
    logo: '',
    initial: 'E',
    color: '#F43F5E',
    price: 78.21,
    priceChange: 2.1,
    marketCap: '14.1B',
    aiScore: 77,
    scoreChange: 2.1,
    rating: 'BUY',
    industry: 'Events & Ticketing',
    sentiment: 69,
    downloads: '310.5K',
    peRatio: 24.8
  }
];

// Screen 1: Build Your Portfolio - Top Recommendations
export const PORTFOLIO_RECOMMENDATIONS = [
  {
    id: 'qdel',
    name: 'QuidelOrtho',
    symbol: 'QDEL',
    initial: 'Q',
    color: '#0EA5E9',
    price: 147.96,
    score: 28,
    change: '+4.2%',
    changeNum: 4.2,
    weight: 20
  },
  {
    id: 'mtch',
    name: 'Match',
    symbol: 'MTCH',
    initial: 'M',
    color: '#EC4899',
    price: 127.12,
    score: 18,
    change: '+2.1%',
    changeNum: 2.1,
    weight: 20
  },
  {
    id: 'len',
    name: 'Lennid',
    symbol: 'LEN',
    initial: 'L',
    color: '#8B5CF6',
    price: 94.50,
    score: 56,
    change: '+7.8%',
    changeNum: 7.8,
    weight: 25
  },
  {
    id: 'eb',
    name: 'Eventbrite',
    symbol: 'EB',
    initial: 'E',
    color: '#F43F5E',
    price: 78.21,
    score: 71,
    change: '+2.1%',
    changeNum: 2.1,
    weight: 15
  },
  {
    id: 'googl',
    name: 'Google',
    symbol: 'GOOGL',
    initial: 'G',
    color: '#EA4335',
    price: 147.11,
    score: 28,
    change: '+2.2%',
    changeNum: 2.2,
    weight: 20
  }
];

// Screen 2: Top Stocks - Reddit Mentions
export const REDDIT_STOCKS_DATA = [
  {
    id: 'qdel',
    name: 'QuidelOrtho',
    symbol: 'QDEL',
    initial: 'Q',
    color: '#0EA5E9',
    price: 147.96,
    mentions: 28,
    change: '+4.2%',
    changeNum: 4.2,
    bullish: 78,
    industry: 'Healthcare'
  },
  {
    id: 'mtch',
    name: 'Match',
    symbol: 'MTCH',
    initial: 'M',
    color: '#EC4899',
    price: 127.12,
    mentions: 18,
    change: '+2.1%',
    changeNum: 2.1,
    bullish: 65,
    industry: 'Consumer Tech'
  },
  {
    id: 'len',
    name: 'Lennid',
    symbol: 'LEN',
    initial: 'L',
    color: '#8B5CF6',
    price: 94.50,
    mentions: 56,
    change: '+7.8%',
    changeNum: 7.8,
    bullish: 84,
    industry: 'Real Estate'
  },
  {
    id: 'eb',
    name: 'Eventbrite',
    symbol: 'EB',
    initial: 'E',
    color: '#F43F5E',
    price: 78.21,
    mentions: 71,
    change: '+2.1%',
    changeNum: 2.1,
    bullish: 72,
    industry: 'Technology'
  },
  {
    id: 'googl',
    name: 'Google',
    symbol: 'GOOGL',
    initial: 'G',
    color: '#EA4335',
    price: 147.11,
    mentions: 28,
    change: '+2.2%',
    changeNum: 2.2,
    bullish: 81,
    industry: 'Technology'
  },
  {
    id: 'msft',
    name: 'Microsoft',
    symbol: 'MSFT',
    initial: 'M',
    color: '#00A4EF',
    price: 347.56,
    mentions: 46,
    change: '+1.8%',
    changeNum: 1.8,
    bullish: 75,
    industry: 'Enterprise Tech'
  },
  {
    id: 'aapl',
    name: 'Apple',
    symbol: 'AAPL',
    initial: 'A',
    color: '#111111',
    price: 187.50,
    mentions: 92,
    change: '+14.5%',
    changeNum: 14.5,
    bullish: 88,
    industry: 'Consumer Tech'
  },
  {
    id: 'tsla',
    name: 'Tesla',
    symbol: 'TSLA',
    initial: 'T',
    color: '#E82127',
    price: 248.50,
    mentions: 145,
    change: '+8.3%',
    changeNum: 8.3,
    bullish: 69,
    industry: 'Automotive / EV'
  }
];

// Screen 3: Top Stock Alerts - July 30
export const STOCK_ALERTS_DATA = [
  {
    id: 'alt-1',
    traderName: 'Robert Anderson',
    traderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    stockName: 'Google Stock',
    symbol: 'GOOGL',
    changePercent: '+16.8%',
    isPositive: true,
    timeframe: 'Tuesday, 7:25 AM - 4:02 PM',
    triggerPrice: '$154.20',
    targetPrice: '$180.00',
    action: 'Strong Buy Signal Triggered'
  },
  {
    id: 'alt-2',
    traderName: 'Jackson Ahmed',
    traderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    stockName: 'Dropbox Stock',
    symbol: 'DBX',
    changePercent: '-28.9%',
    isPositive: false,
    timeframe: 'Monday, 2:12 AM - 3:11 PM',
    triggerPrice: '$28.40',
    targetPrice: '$20.10',
    action: 'Web Traffic Decline Threshold Hit'
  },
  {
    id: 'alt-3',
    traderName: 'Albert Williamson',
    traderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    stockName: 'Slack Stock',
    symbol: 'WORK',
    changePercent: '+24.2%',
    isPositive: true,
    timeframe: 'Sunday, 4:11 AM - 8:33 PM',
    triggerPrice: '$42.10',
    targetPrice: '$52.30',
    action: 'Job Postings + Hiring Spike Detected'
  },
  {
    id: 'alt-4',
    traderName: 'Jeromy Brown',
    traderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    stockName: 'QuidelOrtho Stock',
    symbol: 'QDEL',
    changePercent: '-11.0%',
    isPositive: false,
    timeframe: 'Thursday, 2:26 AM - 5:12 PM',
    triggerPrice: '$165.00',
    targetPrice: '$147.00',
    action: 'Glassdoor Sentiment Divergence'
  }
];

// Screen 5 & 8: Netflix - App Downloads Deep Dive Data
export const NETFLIX_APP_DOWNLOADS = {
  ticker: 'NFLX',
  name: 'Netflix',
  currentPrice: 397.42,
  priceChange: '+4.2%',
  headlineDownloads: '257,892',
  yearChange: '-1.2% (1Y)',
  monthChange: '+4.2% (30D)',
  chartPoints: [
    { date: 'Nov 01', downloads: 224000, label: 'Nov 2022' },
    { date: 'Nov 15', downloads: 231500, label: 'Mid Nov' },
    { date: 'Dec 01', downloads: 242000, label: 'Dec 2022' },
    { date: 'Dec 15', downloads: 258000, label: 'Holiday Peak' },
    { date: 'Dec 30', downloads: 269000, label: 'End Dec' },
    { date: 'Jan 15', downloads: 245000, label: 'Jan 2023' },
    { date: 'Feb 01', downloads: 238000, label: 'Feb 2023' },
    { date: 'Feb 20', downloads: 228000, label: 'Late Feb' },
    { date: 'Mar 15', downloads: 234414, label: 'Mar 2023' },
    { date: 'Apr 01', downloads: 241000, label: 'Apr 2023' },
    { date: 'Apr 25', downloads: 248900, label: 'End Apr' },
    { date: 'May 10', downloads: 261000, label: 'May 2023' },
    { date: 'May 28', downloads: 272000, label: 'Peak May' },
    { date: 'Jun 10', downloads: 254000, label: 'Jun 2023' },
    { date: 'Jun 25', downloads: 257892, label: 'Jun 24, 2023 (Latest)' }
  ],
  similarCompanies: [
    {
      id: 'dis',
      name: 'Disney',
      symbol: 'DIS',
      initial: 'D',
      color: '#113CCF',
      downloads: '632,920',
      change: '+7.3%',
      isPositive: true
    },
    {
      id: 'shop',
      name: 'Shopify',
      symbol: 'SHOP',
      initial: 'S',
      color: '#95BF47',
      downloads: '425,710',
      change: '-2.0%',
      isPositive: false
    },
    {
      id: 'hubs',
      name: 'HubSpot',
      symbol: 'HUBS',
      initial: 'H',
      color: '#FF7A59',
      downloads: '33,900',
      change: '+7.5%',
      isPositive: true
    },
    {
      id: 'slack',
      name: 'HubSpot (Work)',
      symbol: 'HUBS',
      initial: 'H',
      color: '#4A154B',
      downloads: '4,420',
      change: '-7.1%',
      isPositive: false
    },
    {
      id: 'ever',
      name: 'Evernote',
      symbol: 'EVER',
      initial: 'E',
      color: '#00A82D',
      downloads: '52,287',
      change: '+9.5%',
      isPositive: true
    }
  ],
  monthOverMonth: [
    { month: 'June 2023', downloads: '258,810', change: '+4.2%', isPositive: true },
    { month: 'May 2023', downloads: '272,000', change: '-1.5%', isPositive: false },
    { month: 'April 2023', downloads: '248,900', change: '+3.1%', isPositive: true },
    { month: 'March 2023', downloads: '234,414', change: '-', isPositive: null }
  ],
  metrics: [
    { id: '2y-ret', label: '2-Yr return (vs S&P)', value: '+38.2%', isPositive: true },
    { id: 'mkt-cap', label: 'Market Capitalization', value: '204.1B', isPositive: null },
    { id: 'p-to-b', label: 'Price to Book', value: '7.82x', isPositive: null },
    { id: 'rsi', label: 'RSI (14)', value: '46.9', isPositive: null },
    { id: 'pe-ltm', label: 'P/E (LTM 10-Yr Growth)', value: '31.8', isPositive: null },
    { id: 'p-to-cf', label: 'Price to Cash Flow', value: '15.0', isPositive: null },
    { id: 'oper-res', label: 'Oper. Res Q4 22', value: '44.8', isPositive: null },
    { id: 'net-profit', label: 'Net Profit Q4 22', value: '2.8B', isPositive: true },
    { id: 'beta', label: '2-Yr Beta', value: '0.52', isPositive: null },
    { id: 'ps-ratio', label: 'P/S', value: '15.1', isPositive: null },
    { id: 'mfi', label: 'MFI', value: '60.1', isPositive: null },
    { id: 'macd', label: 'MACD / Signal', value: '+0.4 / -0.18', isPositive: true }
  ]
};

// Alternative Data Modules
export const ALTERNATIVE_DATA_CATEGORIES = [
  { id: 'price-prediction', name: 'Price Prediction', icon: 'TrendingUp', count: '142 Models Active' },
  { id: 'job-post', name: 'Job Postings', icon: 'Briefcase', count: '+12.4% Tech Hiring MoM' },
  { id: 'sentiment', name: 'Sentiment Analysis', icon: 'Heart', count: '89.4M Data Points Daily' },
  { id: 'app-downloads', name: 'App Downloads', icon: 'Smartphone', count: '240 App Store Integrations' },
  { id: 'web-traffic', name: 'Webpage Traffic', icon: 'Globe', count: '1.2B Monthly Visits Tracked' },
  { id: 'customer-reviews', name: 'Customer Reviews', icon: 'Star', count: '4.8/5.0 Overall Consumer Avg' },
  { id: 'employee-rating', name: 'Employee Rating', icon: 'Award', count: 'Glassdoor Sentiment Model' },
  { id: 'google-ads', name: 'Google Adspend', icon: 'DollarSign', count: 'Estimated Campaign Outlays' },
  { id: 'google-trends', name: 'Google Trends', icon: 'Flame', count: 'Search Velocity Breakdown' },
  { id: 'linkedin', name: 'LinkedIn Employees', icon: 'Users', count: 'Headcount Net Additions' },
  { id: 'lobbying', name: 'Lobbying Spend', icon: 'Landmark', count: 'Federal Filings & Disclosures' }
];
